---
name: Syntax Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  syntax:
    name: Ansible Syntax Check
    runs-on: ubuntu-latest

    steps:
      - name: Check out the codebase
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ansible-core molecule molecule-plugins[docker]

      - name: Run syntax check
        run: molecule syntax
